apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress-db
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Abhikakadiya2301/ICA_3/'
    targetRevision: master
    path: ICA_3/db
    helm:
      valueFiles:
        - values.yaml
        - templates/secrets.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: db
  syncPolicy:
    automated:
      prune: true
      selfHeal: true