apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-proxy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Abhikakadiya2301/ICA_3.git'
    targetRevision: master
    path: nginx
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: nginx-proxy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true