apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Abhikakadiya2301/ICA_3.git'
    targetRevision: master
    path: wp
    helm:
      valueFiles:
        - values.yaml
        - templates/secrets.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: wp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true