•	replicaCount: 1
•	
•	image:
•	  repository: mariadb
•	  tag: latest
•	  pullPolicy: IfNotPresent
•	
•	service:
•	  type: ClusterIP
•	  port: 3306
•	
•	env:
•	  MYSQL_ROOT_PASSWORD: "admin"
•	  MYSQL_DATABASE: wordpress
•	  MYSQL_USER: wp_user
•	  MYSQL_PASSWORD: "admin"
•	
•	namespace: db
•	
•	labels:
•	  id: c0912546
•	  app: database
•	  env: dev
